// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaksdIjXEU6LDNmeTbo94pCDN_codunK0',
    appId: '1:715976752753:web:5fabf586692a21690fa5d0',
    messagingSenderId: '715976752753',
    projectId: 'carrierroadmapbuilder',
    authDomain: 'carrierroadmapbuilder.firebaseapp.com',
    storageBucket: 'carrierroadmapbuilder.firebasestorage.app',
    measurementId: 'G-G8SFQWG09W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKG5PPK_1eMDl_oKWmqRYaJKhA-hf7Klk',
    appId: '1:715976752753:android:d5a6b54a82e571010fa5d0',
    messagingSenderId: '715976752753',
    projectId: 'carrierroadmapbuilder',
    storageBucket: 'carrierroadmapbuilder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5GzTdpX3yRJzvO_E97vIH4BiTYGAJlCo',
    appId: '1:715976752753:ios:8c6039cf89b9f3060fa5d0',
    messagingSenderId: '715976752753',
    projectId: 'carrierroadmapbuilder',
    storageBucket: 'carrierroadmapbuilder.firebasestorage.app',
    iosClientId: '715976752753-j5bfiv3s3bo6gv2mu14fbiao997fr63e.apps.googleusercontent.com',
    iosBundleId: 'com.carrierroadmap.arnav.carrierbuilder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5GzTdpX3yRJzvO_E97vIH4BiTYGAJlCo',
    appId: '1:715976752753:ios:8c6039cf89b9f3060fa5d0',
    messagingSenderId: '715976752753',
    projectId: 'carrierroadmapbuilder',
    storageBucket: 'carrierroadmapbuilder.firebasestorage.app',
    iosClientId: '715976752753-j5bfiv3s3bo6gv2mu14fbiao997fr63e.apps.googleusercontent.com',
    iosBundleId: 'com.carrierroadmap.arnav.carrierbuilder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaksdIjXEU6LDNmeTbo94pCDN_codunK0',
    appId: '1:715976752753:web:18a8df4577a91cc20fa5d0',
    messagingSenderId: '715976752753',
    projectId: 'carrierroadmapbuilder',
    authDomain: 'carrierroadmapbuilder.firebaseapp.com',
    storageBucket: 'carrierroadmapbuilder.firebasestorage.app',
    measurementId: 'G-QGZD6DHG4T',
  );

}